import type { Metadata } from "next";
import "./globals.css";
import MainContainer from "./ui/main-container/main-container";
import { Providers } from "./providers";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Providers>
					<MainContainer>{children}</MainContainer>
				</Providers>
			</body>
		</html>
	);
}
