import type { Metadata } from "next";
import "./globals.css";

import { Providers } from "./providers";
import MainContainer from "./components/main-container";
import { getServerAuthSession } from "@/server/auth";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const authSession = await getServerAuthSession();

	return (
		<html lang="en">
			<body>
				<Providers>
					<Suspense fallback={<Loading />}>
						{authSession?.user ? (
							<MainContainer>{children}</MainContainer>
						) : (
							children
						)}
					</Suspense>
				</Providers>
			</body>
		</html>
	);
}
